channels:
  - defaults
  - anaconda
  - conda-forge
  # - h2oai
dependencies:
  - python=3.7
  - bokeh
  # - h2o=3.30.0.4
  - joblib
  - loguru
  - openjdk
  - mlflow
  - pandas
  - scikit-learn
  - pip
  - pip:
      - h2o
      - mxnet
      - autogluon.tabular
