channels:
  - defaults
  - auto
  - conda-forge
dependencies:
  - ipykernel
  - black
  - flake8
  - isort
  - jupyter
  - pytest
  - mlflow
  - pip
  - pip:
    - autoflake
    - python-dotenv
