name: automl
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - bokeh==2.0.1
  - joblib
  - loguru
  - openjdk
  - mlflow
  - pandas
  - scikit-learn
  - pip
  - pip:
      - h2o
      - mxnet
      - autogluon.tabular
