services:
  predictor_a: &default
    image: ${DOCKER_NAME}
    environment:
      - DISABLE_NGINX=true
      - GUNICORN_CMD_ARGS=--bind=0.0.0.0:8000 --workers=1
    build:
      context: container
      dockerfile: Dockerfile
    volumes:
      - ${MLFLOW_AUTOGLUON}:/models
      - ./log:/app/log
    expose:
      - "8000"
  predictor_b:
    <<: *default
    volumes:
      - ${MLFLOW_H2OAUTOML}:/models
      - ./log:/app/log
  coordinator:
    <<: *default
    environment:
      - GUNICORN_CMD_ARGS=--bind=0.0.0.0:8000 --workers=1
      - PREDICTOR_A_URI=http://predictor_a:8000/invocations
      - PREDICTOR_B_URI=http://predictor_b:8000/invocations
    volumes:
      - ${MLFLOW_COORDINATOR}:/models
      - ./log:/app/log
    depends_on:
      - predictor_a
      - predictor_b
    ports:
      - "${API_PORT}:8000"
