# -*- mode: makefile -*-

include .trained.env
export

SHELL := /bin/bash
DOCKER_NAME=automl

list_artifacts:
	tree $(MLFLOW_MODEL)

serve:
	mlflow models serve -m $(MLFLOW_MODEL)

.PHONY: test

test_h2o:
	mlflow run h2o_mlflow -e test

test_autogluon:
	mlflow run autogluon_mlflow -e test

build_docker:
	mlflow models build-docker -m $(MLFLOW_MODEL) -n $(DOCKER_NAME)

serve_docker:
	docker run -p 5000:8000 -e DISABLE_NGINX=true -e GUNICORN_CMD_ARGS='--bind=0.0.0.0 --workers=1' $(DOCKER_NAME)
