@startuml
autonumber
skinparam defaultFontName Osaka
' scale 2
' left to right direction
' title mlflowを使った学習・予測
actor "AI trainer" as trainer
actor "API user" as user
box "Local Dev"
participant preprocess
participant "ML model" as model
end box
box "MLflow" #LightGreen
participant "Track metrics/Log artifacts" as mlflow
participant "Models" as builder
participant "Serving" as serving
end box
' trainer -> mlflow: Start experiment
trainer -> preprocess: Preprocess train/test data
trainer -> model: Fit the ML model
trainer -> mlflow: Log preproc and ML models
mlflow -> builder: Save
trainer -> serving: Deploy service (REST API)
serving -> builder: Use
user -> serving: Prediction data JSON
' serving -> preprocess: Preprocess prediction data
' serving -> model: Predict
' serving -> user: Prediction result JSON
@enduml
