channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - mlflow=1.23
  - pandas=1.3
  - joblib
  - loguru
  - gcc_linux-64
  - scikit-learn
  - python-dotenv
  - pip
  - pip:
      # - mxnet_cu101<2.0.0
      - mxnet<2.0.0
      - autogluon.tabular==0.3.2b20220126
