channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - mxnet<2.0.0
  - mlflow=1.25
  - pandas=1.3
  - joblib
  - loguru
  # - gcc_linux-64
  - scikit-learn
  - python-dotenv
  - pip #=21.2.4
  - pip:
    - autogluon.tabular>=0.4.0 # autogluon requires Py 3.7, 3.8 or 3.9
    - httpx