channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - mlflow=1.23
  - pandas=1.3
  - h2oai::h2o=3.30
  - openjdk=11.0
  - joblib
  - loguru
  - scikit-learn
  - python-dotenv
  - pytest
  - pip
