channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - mlflow>=1.25
  - pandas>=1.4
  - h2oai::h2o>=3.36
  - openjdk=11.0
  - joblib
  - loguru
  - scikit-learn
  - python-dotenv
  - pytest
  - pip
